# Generated by Django 5.1.7 on 2025-03-24 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255, unique=True)),
                ('template_data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventbrite_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='chief_planner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'captain'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EventbriteToken',
        ),
    ]
