# Generated by Django 5.1.7 on 2025-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventtemplate_remove_event_eventbrite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
