# Generated by Django 5.1.7 on 2025-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Assign', max_length=50),
        ),
    ]
