# Generated by Django 5.1.7 on 2025-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
