# Generated by Django 5.1.7 on 2025-04-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='assigned_to',
        ),
    ]
